### ISSUE TITLE
htcondor trying to use cgroups?

### ISSUE THREAD

**Issue by hinchliff** [DS-CNAF/htcondor-docker-centos#1]
I sent the following email to `htcondor-admin@cs.wisc.edu`, as I expect that this is more of a problem with htcondor.  However, the docker containers may want to adjust the htcondor configuration settings to match.

If anyone here has information on ways to correct the configuration, please let me know.

>I have an issue where it looks like I'm getting cgroup errors when trying to run a job, even though I haven't configured condor to use cgroups.
>
>The condor docs seem to say that cgroups won't be used unless you explicitly turn it on:
http://research.cs.wisc.edu/htcondor/manual/v8.6/3_14Setting_Up.html#SECTION0041412000000000000000
>
>Is that the case?  How can I configure condor to not use cgroups?
>
>
>I'm actually running condor through docker containers, from:
https://github.com/DS-CNAF/htcondor-docker-centos
>
>The version of condor is 8.6.1:
$CondorVersion: 8.6.1 Mar 01 2017 BuildID: 398585 $
$CondorPlatform: x86_64_RedHat7 $
>
>When I run the containers normally, I get the following errors on job submission.
>
>the submitter ShadowLog says:
> ```
> 03/30/17 18:57:45 (2.0) (13181): Request to run on slot1@condorexecutor <172.19.0.4:9618?addrs=172.19.0.4-9618+[--1]-9618&noUDP&sock=11_1fa1_3> was ACCEPTED
> 03/30/17 18:57:46 (2.0) (13181): File transfer completed successfully.
> 03/30/17 18:57:47 (2.0) (13181): ERROR "Error from slot1@condorexecutor: Create_Process failed to register the job with the ProcD" at line 570 in file /slots/02/dir_2002826/userdir/.tmpBwQbLC/BUILD/condor-8.6.1/src/condor_shadow.V6.1/pseudo_ops.cpp
> ```
>while the executor StarterLog.slot1 says:
> ```
> 03/30/17 18:38:47 (pid:17380) Running job as user nobody
> 03/30/17 18:38:47 (pid:17396) Result of "track_family_via_cgroup" operation from ProcD: ERROR: No cgroup available for tracking
> 03/30/17 18:38:47 (pid:17396) Create_Process: error tracking family with root 17396 via cgroup htcondor/condor_var_lib_condor_execute_slot1@condorexecutor
> 03/30/17 18:38:47 (pid:17380) Create_Process(/var/lib/condor/execute/dir_17380/condor_exec.exe): child failed because it failed to register itself with the ProcD
> 03/30/17 18:38:47 (pid:17380) ERROR "Create_Process failed to register the job with the ProcD" at line 632 in file /slots/02/dir_2002826/userdir/.tmpBwQbLC/BUILD/condor-8.6.1/src/condor_starter.V6.1/os_proc.cpp
> 03/30/17 18:38:47 (pid:17380) ShutdownFast all jobs.
> 03/30/17 18:38:47 (pid:17380) condor_read() failed: recv(fd=9) returned -1, errno = 104 Connection reset by peer, reading 5 bytes from <172.19.0.3:45732>.
>```
>I could run the docker containers as --privileged, and then the jobs seem to be submitted and run to successful completion.  But I would much rather disable the use of cgroups.  (And of course, the documentation seems to suggest the use of cgroups should not have been attempted until/unless I enabled them.)

**Comment by rfc1459** [comment]
Work on this image has been stale since we moved to a [Debian-based image](https://github.com/DS-CNAF/HTCondor-docker-debian), so I expect more issues with recent HTCondor versions aside from this one.

While we're probably going to update this image sometime in the future, it won't probably happen in a short timeframe. In the meantime, could you try the Debian-based image and see if the issue is there as well?

**Comment by hinchliff** [comment]
The debian based image seemed to fail to even startup, with the newer version of HTCondor:

```
root@condorsubmitter:/# condor_version
$CondorVersion: 8.6.1 Mar 01 2017 BuildID: 398585 $
$CondorPlatform: x86_64_Ubuntu14 $

root@condorsubmitter:/# condor_status
Error: communication error
CEDAR:6001:Failed to connect to <172.19.0.2:9618>

root@condorsubmitter:/# ping condormaster
PING condormaster (172.19.0.2) 56(84) bytes of data.
64 bytes from condormaster.htcondor (172.19.0.2): icmp_seq=1 ttl=64 time=0.144 ms
```

Master CollectorLog:
```
03/31/17 13:01:08 Setting maximum file descriptors to 10240.
03/31/17 13:01:08 ******************************************************
03/31/17 13:01:08 ** condor_collector (CONDOR_COLLECTOR) STARTING UP
03/31/17 13:01:08 ** /usr/sbin/condor_collector
03/31/17 13:01:08 ** SubsystemInfo: name=COLLECTOR type=COLLECTOR(3) class=DAEMON(1)
03/31/17 13:01:08 ** Configuration: subsystem:COLLECTOR local:<NONE> class:DAEMON
03/31/17 13:01:08 ** $CondorVersion: 8.6.1 Mar 01 2017 BuildID: 398585 $
03/31/17 13:01:08 ** $CondorPlatform: x86_64_Ubuntu14 $
03/31/17 13:01:08 ** PID = 50
03/31/17 13:01:08 ** Log last touched time unavailable (No such file or directory)
03/31/17 13:01:08 ******************************************************
03/31/17 13:01:08 Using config source: /etc/condor/condor_config
03/31/17 13:01:08 Using local config sources:
03/31/17 13:01:08    /etc/condor/condor_config.local
03/31/17 13:01:08 config Macros = 65, Sorted = 65, StringBytes = 1581, TablesBytes = 2380
03/31/17 13:01:08 CLASSAD_CACHING is ENABLED
03/31/17 13:01:08 Daemon Log is logging: D_ALWAYS D_ERROR
03/31/17 13:01:08 SharedPortEndpoint: waiting for connections to named socket collector
03/31/17 13:01:08 DaemonCore: non-shared command socket at <172.19.0.2:36184>
03/31/17 13:01:08 Daemoncore: Listening at <0.0.0.0:36184> on TCP (ReliSock) and UDP (SafeSock).
03/31/17 13:01:08 DaemonCore: non-shared command socket at <[::1]:36184>
03/31/17 13:01:08 WARNING: Condor is running on a loopback address
03/31/17 13:01:08          of this machine, and may not visible to other hosts!
03/31/17 13:01:08 Daemoncore: Listening at <[::]:36184> on TCP (ReliSock) and UDP (SafeSock).
03/31/17 13:01:08 SharedPortEndpoint: failed to open /var/lock/condor/shared_port_ad: No such file or directory
03/31/17 13:01:08 SharedPortEndpoint: did not successfully find SharedPortServer address. Will retry in 60s.
03/31/17 13:01:08 DaemonCore: private command socket at <172.19.0.2:0?sock=collector>
03/31/17 13:01:08 In ViewServer::Init()
03/31/17 13:01:08 In CollectorDaemon::Init()
03/31/17 13:01:08 In ViewServer::Config()
03/31/17 13:01:08 In CollectorDaemon::Config()
03/31/17 13:01:08 ERROR "Unable to determine my own address, aborting rather than hang.  You may need to make sure the shared port daemon is running first." at line 1369 in file /slots/02/dir_2435919/sources/src/condor_collector.V6/collector.cpp
```

Master MasterLog:
```
03/31/17 13:01:08 ******************************************************
03/31/17 13:01:08 ** condor_master (CONDOR_MASTER) STARTING UP
03/31/17 13:01:08 ** /usr/sbin/condor_master
03/31/17 13:01:08 ** SubsystemInfo: name=MASTER type=MASTER(2) class=DAEMON(1)
03/31/17 13:01:08 ** Configuration: subsystem:MASTER local:<NONE> class:DAEMON
03/31/17 13:01:08 ** $CondorVersion: 8.6.1 Mar 01 2017 BuildID: 398585 $
03/31/17 13:01:08 ** $CondorPlatform: x86_64_Ubuntu14 $
03/31/17 13:01:08 ** PID = 46
03/31/17 13:01:08 ** Log last touched time unavailable (No such file or directory)
03/31/17 13:01:08 ******************************************************
03/31/17 13:01:08 Using config source: /etc/condor/condor_config
03/31/17 13:01:08 Using local config sources:
03/31/17 13:01:08    /etc/condor/condor_config.local
03/31/17 13:01:08 config Macros = 64, Sorted = 64, StringBytes = 1538, TablesBytes = 2344
03/31/17 13:01:08 CLASSAD_CACHING is OFF
03/31/17 13:01:08 Daemon Log is logging: D_ALWAYS D_ERROR
03/31/17 13:01:08 SharedPortEndpoint: waiting for connections to named socket 46_71da
03/31/17 13:01:08 SharedPortEndpoint: failed to open /var/lock/condor/shared_port_ad: No such file or directory
03/31/17 13:01:08 SharedPortEndpoint: did not successfully find SharedPortServer address. Will retry in 60s.
03/31/17 13:01:08 DaemonCore: private command socket at <172.19.0.2:0?sock=46_71da>
03/31/17 13:01:08 Adding SHARED_PORT to DAEMON_LIST, because USE_SHARED_PORT=true (to disable this, set AUTO_INCLUDE_SHARED_PORT_IN_DAEMON_LIST=False)
03/31/17 13:01:08 Master restart (GRACEFUL) is watching /usr/sbin/condor_master (mtime:1488432304)
03/31/17 13:01:08 /usr/libexec/condor/condor_shared_port: Cannot execute (errno=2, No such file or directory)
03/31/17 13:01:08 restarting /usr/libexec/condor/condor_shared_port in 10 seconds
03/31/17 13:01:08 Timer -1 not found
03/31/17 13:01:08 SharedPortEndpoint: failed to open /var/lock/condor/shared_port_ad: No such file or directory
03/31/17 13:01:08 Started DaemonCore process "/usr/sbin/condor_collector", pid and pgroup = 50
03/31/17 13:01:08 Waiting for /var/log/condor/.collector_address to appear.
03/31/17 13:01:08 attempt to connect to <172.19.0.2:9618> failed: Connection refused (connect errno = 111).
03/31/17 13:01:08 ERROR: SECMAN:2003:TCP connection to collector condormaster failed.
03/31/17 13:01:08 Failed to start non-blocking update to <172.19.0.2:9618>.
03/31/17 13:01:08 systemd watchdog notification support not available.
03/31/17 13:01:08 DefaultReaper unexpectedly called on pid 50, status 1024.
03/31/17 13:01:08 The COLLECTOR (pid 50) exited with status 4
03/31/17 13:01:08 Sending obituary for "/usr/sbin/condor_collector"
03/31/17 13:01:08 my_popenv: Failed to exec in child, errno=2 (No such file or directory)
03/31/17 13:01:08 Failed to launch mailer process: /bin/mail
03/31/17 13:01:08 restarting /usr/sbin/condor_collector in 10 seconds
03/31/17 13:01:08 attempt to connect to <172.19.0.2:9618> failed: Connection refused (connect errno = 111).
03/31/17 13:01:08 ERROR: SECMAN:2003:TCP connection to collector condormaster failed.
03/31/17 13:01:08 Failed to start non-blocking update to <172.19.0.2:9618>.
```

**Comment by hinchliff** [comment]
I received the following helpful information from Todd Tannenbaum on the UW-Madison HTCondor Team (shared with permission), which forms the basis of the pull-request for this issue.

>> I have an issue where it looks like I'm getting cgroup errors when trying to run a job, even though I haven't configured condor to use cgroups.
>>
>> The condor docs seem to say that cgroups won't be used unless you explicitly turn it on:
>>http://research.cs.wisc.edu/htcondor/manual/v8.6/3_14Setting_Up.html#SECTION0041412000000000000000
>>
>> Is that the case?
>
>It used to be, but as of HTCondor v8.5.8 cgroups is enabled by default.
>While the version history in the Manual noted this change, updating the  documentation in section 3.14 was apparently not done.  Thank you for  pointing this out, we will fix it for the next release as I created on ticket on this issue:
>  https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6210
>
>> How can I configure condor to not use cgroups?
>>
>
>In your condor_config file(s), add the following:
>```
>   # Disable HTCondor's cgroup support by defining
>   # the base cgroup as an empty string.
>   BASE_CGROUP=
>```
